# Generated by Django 2.2.6 on 2020-03-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='city',
        ),
    ]
