# Generated by Django 2.2.6 on 2020-03-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_remove_schedule_list_for_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListForSchedule',
        ),
    ]
