# Generated by Django 2.2.6 on 2020-03-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20200311_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_app.City'),
        ),
    ]
