# Generated by Django 2.2.6 on 2020-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_delete_listforschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='text',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
