# Generated by Django 2.2.6 on 2020-03-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_auto_20200316_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='weather_app.List')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
